### ISSUE TITLE
加密文件自动释放是什么意思

### ISSUE THREAD

**Issue by banduoba** [uk0/file_encryption#3]
请问下加密后的文件自动释放是什么意思呢 自动解密么

**Comment by zijianrs** [comment]
我的理解是加密后的文件可以在不依赖其他工具的情况下自动解密
比如加密后生成的文件是 encryption ，直接运行这个文件可以进行解密

**Comment by uk0** [comment]
> 我的理解是加密后的文件可以在不依赖其他工具的情况下自动解密 比如加密后生成的文件是 encryption ，直接运行这个文件可以进行解密

和你想的一样  通过Rust实现了 将加密内容存放在本身的二进制文件内，加密使用DES 很多 目前是 整个文件进行加密 没有进行分块 未来会实现 分块 多线程执行操作


文件A + 加密程序 = 可执行的二进制文件（包含加密内容可以执行输入密码进行释放到当前二进制文件所存在的目录 ）
